// Placeholder data for the studio live-preview iframe. Shown only until the
// admin studio's first postMessage sync replaces it with the real content.
import type {
  AdminAnnouncement,
  AdminCertification,
  AdminGalleryPhoto,
  AdminHomeStep,
  AdminMenuItem,
  AdminSiteSettings,
} from "@/lib/admin-api";

export const DEFAULT_DEAL_PHOTO =
  "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80";

export const DEFAULT_SITE: AdminSiteSettings = {
  hero_heading: "Stack Into",
  hero_script: "Happiness",
  hero_lead: "Warm pancake stacks, made to order in Geelong West and served for relaxed catch-ups.",
  hero_image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=1400&q=85",
  hero_cutout: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
  about_text: "",
  about_heading: "",
  about_script: "",
  about_image_1: "",
  about_image_2: "",
  about_image_3: "",
  about_points: "",
  cta_heading: "Hungry?",
  cta_script: "Book a Table.",
  cta_lead: "Request a table online in seconds — free, with confirmation by email.",
  cta_button_label: "Book a Table",
  cta_button_url: "/booking",
  marquee_words: "",
  footer_tagline: "Fluffy stacks · made to order · Geelong West",
  menu_hero_heading: "Stacks On",
  menu_hero_script: "Stacks.",
  menu_hero_lead: "Explore the current pancake menu and find your next favourite.",
  gallery_hero_kicker: "Feast Your Eyes",
  gallery_hero_heading: "The",
  gallery_hero_script: "Gallery.",
  gallery_hero_lead: "Our food, our space, and the good times in between.",
  booking_hero_kicker: "Request Online — Free & Easy",
  booking_hero_heading: "Book a",
  booking_hero_script: "Table.",
  booking_hero_lead: "Pick a date, pick a time — we'll have the griddle hot when you arrive.",
  address: "18 Pakington Street, Geelong West VIC, Australia",
  phone: "+61 452 135 499",
  whatsapp: "",
  email: "hello@thepancakeclub.com.au",
  abn: "",
  map_embed: "",
  transit_badges: "",
  show_transit_badges: false,
  instagram_url: "",
  facebook_url: "",
  uber_eats_url: "",
  online_ordering_enabled: true,
  online_ordering_disabled_message: "",
  timezone: "Australia/Melbourne",
  theme: "maple",
  custom_primary: "#763a12",
  custom_accent: "#e08600",
  club_hero_kicker: "The Pancake Club · Geelong West",
  club_hero_heading: "Good food.",
  club_hero_script: "Better company.",
  club_hero_lead: "Fluffy homemade stacks, secret tasting invites, and a table always saved for you.",
  club_bento_1_img: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&q=80",
  club_bento_1_badge: "🥞 Fresh Off The Griddle",
  club_bento_1_title: "Signature Stack",
  club_bento_1_sub: "Warm from the griddle",
  club_bento_2_img: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&q=80",
  club_bento_2_badge: "🥞 Sunday Brunch",
  club_bento_2_title: "Brunch Club",
  club_bento_2_sub: "Weekend Table",
  club_bento_3_img: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
  club_bento_3_badge: "☕ Geelong West",
  club_bento_3_title: "Our Parlour",
  club_bento_3_sub: "Open 7 days",
  club_pass_title: "FOUNDING MEMBER PASS · NO. 0824",
  club_pass_sub: "Priority Seasonal Tastings · Secret Drops · Free Forever",
  club_pass_badge: "ALL WELCOME",
};

export const DEFAULT_ANNOUNCEMENT: AdminAnnouncement = {
  id: 1,
  message: "Weekend Brunch Pass — 20% Off All Stacks Before 11am!",
  details: "Saturday & Sunday · early birds enjoy 20% discount",
  link_text: "EXPLORE MENU",
  link_url: "/menu",
  image: DEFAULT_DEAL_PHOTO,
  is_active: true,
  starts_at: null,
  ends_at: null,
};

export const DEFAULT_CERTS: AdminCertification[] = [];

export const DEFAULT_PHOTOS: AdminGalleryPhoto[] = [];

export const DEFAULT_STEPS: AdminHomeStep[] = [
  { id: 1, label: "01", title: "Order Online", text: "Pick your favourite stack and customizations.", image: "", sort_order: 0 },
  { id: 2, label: "02", title: "We Griddle Fresh", text: "Your order is prepared for pickup.", image: "", sort_order: 1 },
  { id: 3, label: "03", title: "Pick Up Hot", text: "Grab your warm stack right on time.", image: "", sort_order: 2 },
];

export const DEFAULT_DISHES: AdminMenuItem[] = [
  {
    slug: "signature-buttermilk",
    name: "Classic Buttermilk Stack",
    description: "Our signature stack with whipped butter & pure maple.",
    price: "14.00",
    tag: "sweet",
    heat: "none",
    kcal: 480,
    protein_g: 14,
    prep_time: "10m",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
    photo: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
    is_featured: true,
    is_available: true,
    sort_order: 0,
  },
  {
    slug: "berry-bliss",
    name: "Berry Bliss",
    description: "Organic blueberries, strawberries, maple syrup, and chantilly cream.",
    price: "17.00",
    tag: "sweet",
    heat: "none",
    kcal: 520,
    protein_g: 12,
    prep_time: "12m",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    photo: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    is_featured: true,
    is_available: true,
    sort_order: 1,
  },
];
