# Generated by Django 5.2.17 on 2026-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(default='🏅', help_text='Emoji shown on the badge', max_length=8)),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Stack Into', max_length=60)),
                ('hero_script', models.CharField(default='Happiness', max_length=60)),
                ('hero_lead', models.TextField(default='We flip the best homemade pancakes in Sydney — griddled to order, stacked high, drowned in real maple.')),
                ('hero_image', models.CharField(default='https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?w=1200&q=80', max_length=300)),
                ('about_text', models.TextField(default="G'day! Every pancake at KRUSH is ladled to order onto a buttered griddle, flipped at exactly the right bubble, and stacked warm with real maple. No shortcuts, no pre-mix — just food that feels good.")),
                ('address', models.CharField(default='123 George Street, Sydney NSW 2000', max_length=200)),
                ('phone', models.CharField(default='(02) 5550 1234', max_length=30)),
                ('email', models.EmailField(default='hello@krushpancakes.com.au', max_length=254)),
                ('abn', models.CharField(default='ABN 00 000 000 000', max_length=40)),
                ('map_embed', models.CharField(default='https://www.google.com/maps?q=George%20Street%20Sydney%20NSW&output=embed', max_length=500)),
                ('instagram_url', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='Australia/Sydney', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
