# Generated by Django 5.2.17 on 2026-08-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettings_about_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('golden', 'Golden Morning'), ('berry', 'Berry Crush'), ('mint', 'Minty Fresh'), ('choco', 'Choc Latte')], default='golden', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.CharField(default='https://images.unsplash.com/photo-1620991565081-82743a5a499c?w=1200&q=80', max_length=300),
        ),
    ]
