# Generated by Django 5.2.17 on 2026-08-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_theme_alter_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_accent',
            field=models.CharField(default='#f2789c', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_primary',
            field=models.CharField(default='#f2be45', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('golden', 'Golden Morning'), ('berry', 'Berry Crush'), ('mint', 'Minty Fresh'), ('choco', 'Choc Latte'), ('custom', 'Custom')], default='golden', max_length=20),
        ),
    ]
