# Generated by Django 5.2.17 on 2026-08-25 04:30

# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_announcement_image_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cutout',
            field=models.CharField(default='/menu/hero-stack.png', max_length=300),
        ),
    ]
