# Generated by Django 5.2.17 on 2026-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_hero_cutout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('golden', 'Golden Morning'), ('berry', 'Berry Crush'), ('mint', 'Minty Fresh'), ('choco', 'Choc Latte'), ('maple', 'Maple Gold'), ('custom', 'Custom')], default='golden', max_length=20),
        ),
    ]
