# Generated by Django 5.2.17 on 2026-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.CharField(blank=True, default='', help_text='Original photo for framed cards; falls back to the cutout when blank', max_length=300),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.CharField(blank=True, help_text='Transparent cutout used on tiles and thumbs, e.g. /menu/berry.png', max_length=300),
        ),
    ]
