# Generated by Django 5.2.17 on 2026-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_menuitem_photo_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_accent',
            field=models.CharField(default='#e08600', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_primary',
            field=models.CharField(default='#efbf38', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('golden', 'Golden Morning'), ('berry', 'Berry Crush'), ('mint', 'Minty Fresh'), ('choco', 'Choc Latte'), ('maple', 'Maple Gold'), ('custom', 'Custom')], default='maple', max_length=20),
        ),
    ]
