# Generated by Django 5.2.17 on 2026-08-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sitesettings_custom_accent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=300)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
