# Generated by Django 5.2.17 on 2026-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_menuitemphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. "Step 1"', max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(default='Fluffy. Golden.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_3',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_points',
            field=models.TextField(blank=True, default='Batter whisked fresh every morning\n100% pure Canadian maple — never syrup-flavoured\nBerries & fruit from local NSW growers\nCloud-light ricotta & buttermilk stacks', help_text='One tick per line. These are public claims — keep them true.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_script',
            field=models.CharField(default='Fully Stacked.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_label',
            field=models.CharField(default='Book a Table', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_url',
            field=models.CharField(default='/booking', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_heading',
            field=models.CharField(default='Hungry?', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_lead',
            field=models.CharField(default='Reserve online in seconds — free, instant confirmation, open 7 days.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_script',
            field=models.CharField(default='Book a Table.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='marquee_words',
            field=models.TextField(blank=True, default='Fluffy Stacks\nReal Maple\nEst. 1999\nFresh Berries\nZero Guilt\nGriddled Daily', help_text='One phrase per line. "Est. 1999" is a factual claim — confirm it.'),
        ),
    ]
