# Generated by Django 5.2.17 on 2026-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_home_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(default='Fluffy stacks · real maple · est. 1999', help_text='Shown in the footer. Contains a founding-year claim — confirm it.', max_length=120),
        ),
    ]
