# Generated by Django 5.2.17 on 2026-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesettings_footer_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='focus',
            field=models.CharField(choices=[('top', 'Keep the top'), ('center', 'Keep the middle'), ('bottom', 'Keep the bottom')], default='center', max_length=8),
        ),
    ]
