# Generated by Django 5.2.17 on 2026-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_galleryphoto_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.CharField(blank=True, default='', help_text='The conditions in one or two lines — days, dine-in or takeaway, which dishes.', max_length=220),
        ),
    ]
