# Generated by Django 5.2.17 on 2026-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_booking_dish_ordering_toggle_ubereats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preselected_dish',
            field=models.CharField(blank=True, default='', help_text='Optional favourite menu items pre-selected by the guest, comma-separated', max_length=400),
        ),
    ]
