# Generated by Django 5.2.17 on 2026-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_booking_preselected_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_hero_heading',
            field=models.CharField(default='Book a', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_hero_kicker',
            field=models.CharField(default='Reserve Online — Free & Instant', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_hero_lead',
            field=models.CharField(default="Pick a date, pick a time — we'll have the griddle hot when you arrive.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_hero_script',
            field=models.CharField(default='Table.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_heading',
            field=models.CharField(default='The', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_kicker',
            field=models.CharField(default='Feast Your Eyes', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_lead',
            field=models.CharField(default='Our food, our space, and the good times in between.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_script',
            field=models.CharField(default='Gallery.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_hero_heading',
            field=models.CharField(default='Stacks On', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_hero_lead',
            field=models.CharField(default='Signature pancake stacks. Griddled to order. Zero regrets.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_hero_script',
            field=models.CharField(default='Stacks.', max_length=60),
        ),
    ]
