# Generated by Django 5.2.17 on 2026-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesettings_booking_hero_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='offers_kicker',
            field=models.CharField(default='On Right Now', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='offers_title',
            field=models.CharField(default="This Week's Offers", help_text='Offers slider heading — the last word is rendered in the accent colour.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_kicker',
            field=models.CharField(default="✨ TODAY'S FEATURED SPECIAL", help_text='Gold kicker above the top deal band headline.', max_length=80),
        ),
    ]
