# Generated by Django 5.2.17 on 2026-09-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesettings_offers_kicker_sitesettings_offers_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='placement',
            field=models.CharField(choices=[('band', 'Top deal band (under the hero — changes often)'), ('slider', 'Offers slider (after the menu — long-running)')], default='slider', max_length=10),
        ),
    ]
