# Generated by Django 5.2.17 on 2026-09-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_announcement_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='card1_dish',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='card2_dish',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
