# Generated by Django 5.2.17 on 2026-09-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_announcement_card1_dish_announcement_card2_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
