# Generated by Django 5.2.17 on 2026-09-05 17:36
#
# Written defensively: a parallel deploy already added these two columns to the
# production database under a different migration name, so the DB half only
# adds each column when it is actually missing (works on sqlite and postgres).

from django.db import migrations, models


def add_columns_if_missing(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        existing = {
            c.name for c in conn.introspection.get_table_description(cursor, "core_sitesettings")
        }
    SiteSettings = apps.get_model("core", "SiteSettings")
    for field_name in ("show_transit_badges", "transit_badges"):
        if field_name not in existing:
            schema_editor.add_field(SiteSettings, SiteSettings._meta.get_field(field_name))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_payment_status_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        # record the fields in Django's model state only…
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='sitesettings',
                    name='show_transit_badges',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='sitesettings',
                    name='transit_badges',
                    field=models.TextField(blank=True, default='🚆 3 min walk from Town Hall\n🚗 2hr Street Parking\n♿ Step-Free Access', help_text='One transit/parking/access chip per line'),
                ),
            ],
            database_operations=[],
        ),
        # …then touch the database only where the columns are truly absent
        migrations.RunPython(add_columns_if_missing, migrations.RunPython.noop),
    ]
