# Generated by Django 5.2.17 on 2026-09-11 11:19

import django.db.models.deletion
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    MenuItem = apps.get_model('core', 'MenuItem')

    cats = [
        {"name": "Sweet Stacks", "slug": "sweet", "icon": "🍯", "sort_order": 1},
        {"name": "Savoury Brunch", "slug": "savoury", "icon": "🥑", "sort_order": 2},
        {"name": "Choc Loaded", "slug": "choc", "icon": "🍫", "sort_order": 3},
    ]
    cat_map = {}
    for c in cats:
        cat_obj, _ = Category.objects.get_or_create(
            slug=c["slug"],
            defaults={"name": c["name"], "icon": c["icon"], "sort_order": c["sort_order"], "is_active": True}
        )
        cat_map[c["slug"]] = cat_obj

    for item in MenuItem.objects.all():
        if item.tag in cat_map:
            item.category = cat_map[item.tag]
            item.save(update_fields=['category'])


def unseed_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_coupon_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, default='🥞', help_text='Emoji or icon identifier, e.g. 🥞, 🍯, 🥑, 🍫, ☕', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='tag',
            field=models.CharField(blank=True, default='sweet', max_length=60),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.category'),
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
