# Generated by Django 5.2.17 on 2026-09-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_category_alter_menuitem_tag_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='order_prep_time',
            field=models.CharField(blank=True, default='15–20 mins', help_text='Estimated preparation and pickup time displayed to customers in cart and checkout', max_length=60),
        ),
    ]
