# Generated by Django 5.2.17 on 2026-09-16 04:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sitesettings_order_prep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=12)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('marketing_consented_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_accepted_at', models.DateTimeField()),
                ('consent_version', models.CharField(default='club-v1', max_length=30)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='club_email_ci_unique')],
            },
        ),
    ]
