# Generated by Django 5.2.17 on 2026-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_club_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_1_badge',
            field=models.CharField(default='🥞 SEASONAL TASTES', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_1_desc',
            field=models.TextField(default='Be the first to preview autumn spiced ricotta hotcakes and summer berry compotes before public menu launch.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_1_title',
            field=models.CharField(default='Seasonal First Tastes', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_2_badge',
            field=models.CharField(default='✨ PARLOUR PERKS', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_2_desc',
            field=models.TextField(default='Occasional unlisted griddle specials, birthday stack treats, and intimate tasting invites for Geelong regulars.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_2_title',
            field=models.CharField(default='Secret Parlour Drops', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_3_badge',
            field=models.CharField(default='💛 ZERO STRINGS', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_3_desc',
            field=models.TextField(default='No loyalty cards to scan, no passwords to memorize. Choose your email preference and opt out anytime with one click.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_benefit_3_title',
            field=models.CharField(default='Always Your Choice', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_1_badge',
            field=models.CharField(default='✨ Fresh Off The Griddle', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_1_img',
            field=models.CharField(default='https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&q=80', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_1_sub',
            field=models.CharField(default='Whipped butter & maple', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_1_title',
            field=models.CharField(default='Signature Stack', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_2_badge',
            field=models.CharField(default='🥞 Sunday Brunch', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_2_img',
            field=models.CharField(default='https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&q=80', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_2_sub',
            field=models.CharField(default='Weekend Table', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_2_title',
            field=models.CharField(default='Brunch Club', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_3_badge',
            field=models.CharField(default='☕ Geelong West', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_3_img',
            field=models.CharField(default='https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_3_sub',
            field=models.CharField(default='Open 7 days', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_bento_3_title',
            field=models.CharField(default='Our Parlour', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_hero_heading',
            field=models.CharField(default='Good food.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_hero_kicker',
            field=models.CharField(default='The Pancake Club · Geelong West', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_hero_lead',
            field=models.CharField(default='Fluffy homemade stacks, secret tasting invites, and a table always saved for you.', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_hero_script',
            field=models.CharField(default='Better company.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_pass_badge',
            field=models.CharField(default='★ ALL WELCOME', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_pass_sub',
            field=models.CharField(default='Priority Seasonal Tastings · Secret Drops · Free Forever', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='club_pass_title',
            field=models.CharField(default='FOUNDING MEMBER PASS · NO. 0824', max_length=80),
        ),
    ]
