# Generated by Django 5.2.17 on 2026-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sitesettings_club_benefit_1_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_2_badge',
            field=models.CharField(default='☕ PARLOUR PERKS', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_1_badge',
            field=models.CharField(default='🥞 Fresh Off The Griddle', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_pass_badge',
            field=models.CharField(default='ALL WELCOME', max_length=40),
        ),
    ]
