# Generated by Django 5.2.17 on 2026-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_sitesettings_club_benefit_2_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
