# Generated by Django 5.2.17 on 2026-09-17 15:28

from django.db import migrations, models


def replace_legacy_sydney_placeholders(apps, schema_editor):
    """Update only untouched legacy defaults; never overwrite staff edits."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    replacements = {
        "hero_lead": (
            "We flip the best homemade pancakes in Sydney — griddled to order, "
            "stacked high, drowned in real maple.",
            "We flip the best homemade pancakes in Geelong — griddled to order, "
            "stacked high, drowned in real maple.",
        ),
        "about_points": (
            "Batter whisked fresh every morning\n"
            "100% pure Canadian maple — never syrup-flavoured\n"
            "Berries & fruit from local NSW growers\n"
            "Cloud-light ricotta & buttermilk stacks",
            "Batter whisked fresh every morning\n"
            "100% pure Canadian maple — never syrup-flavoured\n"
            "Berries & fruit from local Victorian growers\n"
            "Cloud-light ricotta & buttermilk stacks",
        ),
        "address": (
            "123 George Street, Sydney NSW 2000",
            "18 Pakington Street, Geelong West VIC, Australia",
        ),
        "phone": ("(02) 5550 1234", "+61 452 135 499"),
        "map_embed": (
            "https://www.google.com/maps?q=George%20Street%20Sydney%20NSW&output=embed",
            "https://www.google.com/maps?q=18%20Pakington%20Street%2C%20Geelong%20West%20VIC%20Australia&output=embed",
        ),
        "timezone": ("Australia/Sydney", "Australia/Melbourne"),
    }
    for field, (old_value, new_value) in replacements.items():
        SiteSettings.objects.filter(**{field: old_value}).update(**{field: new_value})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_phone_to_clubmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_points',
            field=models.TextField(blank=True, default='Batter whisked fresh every morning\n100% pure Canadian maple — never syrup-flavoured\nBerries & fruit from local Victorian growers\nCloud-light ricotta & buttermilk stacks', help_text='One tick per line. These are public claims — keep them true.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='18 Pakington Street, Geelong West VIC, Australia', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_lead',
            field=models.TextField(default='We flip the best homemade pancakes in Geelong — griddled to order, stacked high, drowned in real maple.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed',
            field=models.CharField(default='https://www.google.com/maps?q=18%20Pakington%20Street%2C%20Geelong%20West%20VIC%20Australia&output=embed', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+61 452 135 499', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(default='Australia/Melbourne', max_length=50),
        ),
        migrations.RunPython(replace_legacy_sydney_placeholders, migrations.RunPython.noop),
    ]
