# Generated by Django 5.2.17 on 2026-09-17 15:31

from django.db import migrations, models


def replace_misleading_confirmation_defaults(apps, schema_editor):
    """Change only the legacy defaults; preserve copy edited by staff."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(
        booking_hero_kicker="Reserve Online — Free & Instant"
    ).update(booking_hero_kicker="Request Online — Free & Easy")
    SiteSettings.objects.filter(
        cta_lead="Reserve online in seconds — free, instant confirmation, open 7 days."
    ).update(
        cta_lead="Request a table online in seconds — free, with confirmation by email."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_sitesettings_about_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='booking_hero_kicker',
            field=models.CharField(default='Request Online — Free & Easy', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_lead',
            field=models.CharField(default='Request a table online in seconds — free, with confirmation by email.', max_length=200),
        ),
        migrations.RunPython(replace_misleading_confirmation_defaults, migrations.RunPython.noop),
    ]
