# Generated by Django 5.2.17 on 2026-09-17 17:46

from django.db import migrations, models


def remove_unverified_demo_content(apps, schema_editor):
    """Remove only known placeholders/demo claims; preserve all staff edits."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    Review = apps.get_model("core", "Review")
    Certification = apps.get_model("core", "Certification")
    Announcement = apps.get_model("core", "Announcement")

    safe_fields = {
        "hero_lead": "Warm pancake stacks, made to order in Geelong West and served for relaxed catch-ups with your favourite people.",
        "about_points": "Made to order on the griddle\nSweet and savoury choices\nDine in or order pickup\nFind us in Geelong West",
        "about_text": "G'day! The Pancake Club is a place for warm stacks, relaxed catch-ups, and good food in Geelong West.",
        "club_bento_1_sub": "Warm from the griddle",
        "footer_tagline": "Fluffy stacks · made to order · Geelong West",
        "marquee_words": "Fluffy Stacks\nGeelong West\nSweet & Savoury\nMade to Order\nBrunch Together\nPickup Ready",
    }
    legacy_values = {
        "hero_lead": [
            "We flip the best homemade pancakes in Geelong — griddled to order, stacked high, drowned in real maple.",
            "We pour our hearts into every stack, so you can enjoy Geelong’s best pancakes with the people you love.",
        ],
        "about_points": [
            "Batter whisked fresh every morning\n100% pure Canadian maple — never syrup-flavoured\nBerries & fruit from local Victorian growers\nCloud-light ricotta & buttermilk stacks",
        ],
        "about_text": [
            "G'day! Every pancake at The Pancake Club is ladled to order onto a buttered griddle, flipped at exactly the right bubble, and stacked warm with real maple. No shortcuts, no pre-mix — just food that feels good.",
        ],
        "club_bento_1_sub": ["Whipped butter & maple"],
        "footer_tagline": [
            "Fluffy stacks · real maple · est. 1999",
            "Fluffy stacks · real maple · Geelong West",
        ],
        "marquee_words": [
            "Fluffy Stacks\nReal Maple\nEst. 1999\nFresh Berries\nZero Guilt\nGriddled Daily",
            "Fluffy Stacks\nReal Maple\nGeelong West\nFresh Berries\nZero Guilt\nGriddled Daily",
        ],
    }
    for field, values in legacy_values.items():
        SiteSettings.objects.filter(**{f"{field}__in": values}).update(
            **{field: safe_fields[field]}
        )

    placeholder_fields = {
        "abn": ["ABN 00 000 000 000"],
        "whatsapp": ["+61 400 000 000"],
        "instagram_url": ["https://www.instagram.com", "https://instagram.com"],
        "facebook_url": ["https://www.facebook.com", "https://facebook.com"],
        "uber_eats_url": ["https://www.ubereats.com", "https://ubereats.com"],
    }
    for field, values in placeholder_fields.items():
        SiteSettings.objects.filter(**{f"{field}__in": values}).update(**{field: ""})

    transit_placeholders = [
        "3 min walk from Town hall\n2hr Street Parking\nStep free access",
        "🚆 3 min walk from Town Hall\n🚗 2hr Street Parking\n♿ Step-Free Access",
    ]
    SiteSettings.objects.filter(transit_badges__in=transit_placeholders).update(
        transit_badges="", show_transit_badges=False
    )

    demo_reviews = [
        ("Sarah M.", "Best pancakes I've had in Geelong, hands down. The stack is cloud-fluffy and the warm maple butter is addictive."),
        ("Daniel K.", "Booked online for a birthday brunch — table was ready on the dot, staff were lovely, and the Choc Overload is a monster. Our new Geelong favourite!"),
        ("Priya S.", "Great vibe, colourful fit-out, quick service. The Lemon Ricotta is genuinely special — light as air and not too sweet."),
        ("Tom B.", "Took the kids on a weekend for the special. Fast, friendly, and the banana caramel stack is dangerously good. Our new family regular."),
        ("Jess W.", "The Big Brekkie Stack lives up to its name. Loved the vibe on Pakington Street. We will definitely be back."),
    ]
    for name, quote in demo_reviews:
        Review.objects.filter(name=name, quote=quote).update(is_approved=False)

    demo_certifications = [
        ("Food Safety Certified", "Victorian Food Safety Standards"),
        ("5-Star Hygiene Rating", "City of Greater Geelong"),
        ("Best Pancakes — Geelong 2025", "Victorian Hospitality Awards"),
        ("HACCP Compliant", "Certified Kitchen"),
        ("Local Produce Partner", "Victorian Farmers' Network"),
    ]
    for title, subtitle in demo_certifications:
        Certification.objects.filter(title=title, subtitle=subtitle).update(is_active=False)

    Announcement.objects.filter(
        message__in=[
            "New Special 20% off this weekend!",
            "Weekend Brunch Pass - 20% off all Stacks before 11Pm",
        ]
    ).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_sitesettings_booking_hero_kicker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='abn',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_points',
            field=models.TextField(blank=True, default='Made to order on the griddle\nSweet and savoury choices\nDine in or order pickup\nFind us in Geelong West', help_text='One tick per line. These are public claims — keep them true.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default="G'day! The Pancake Club is a place for warm stacks, relaxed catch-ups, and good food in Geelong West."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_1_sub',
            field=models.CharField(default='Warm from the griddle', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(default='Fluffy stacks · made to order · Geelong West', help_text='Shown in the footer.', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_lead',
            field=models.TextField(default='Warm pancake stacks, made to order in Geelong West and served for relaxed catch-ups with your favourite people.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='marquee_words',
            field=models.TextField(blank=True, default='Fluffy Stacks\nGeelong West\nSweet & Savoury\nMade to Order\nBrunch Together\nPickup Ready', help_text='One phrase per line.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_transit_badges',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='transit_badges',
            field=models.TextField(blank=True, default='', help_text='One transit/parking/access chip per line'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='uber_eats_url',
            field=models.CharField(blank=True, default='', help_text='Link to Uber Eats store', max_length=300),
        ),
        migrations.RunPython(remove_unverified_demo_content, migrations.RunPython.noop),
    ]
