# Generated by Django 5.2.17 on 2026-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_deactivate_legacy_sydney_demo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_1_badge',
            field=models.CharField(blank=True, default='🥞 SEASONAL TASTES', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_1_desc',
            field=models.TextField(blank=True, default='Be the first to preview autumn spiced ricotta hotcakes and summer berry compotes before public menu launch.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_1_title',
            field=models.CharField(blank=True, default='Seasonal First Tastes', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_2_badge',
            field=models.CharField(blank=True, default='☕ PARLOUR PERKS', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_2_desc',
            field=models.TextField(blank=True, default='Occasional unlisted griddle specials, birthday stack treats, and intimate tasting invites for Geelong regulars.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_2_title',
            field=models.CharField(blank=True, default='Secret Parlour Drops', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_3_badge',
            field=models.CharField(blank=True, default='💛 ZERO STRINGS', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_3_desc',
            field=models.TextField(blank=True, default='No loyalty cards to scan, no passwords to memorize. Choose your email preference and opt out anytime with one click.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_benefit_3_title',
            field=models.CharField(blank=True, default='Always Your Choice', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_1_badge',
            field=models.CharField(blank=True, default='🥞 Fresh Off The Griddle', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_1_img',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&q=80', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_1_sub',
            field=models.CharField(blank=True, default='Warm from the griddle', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_1_title',
            field=models.CharField(blank=True, default='Signature Stack', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_2_badge',
            field=models.CharField(blank=True, default='🥞 Sunday Brunch', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_2_img',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&q=80', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_2_sub',
            field=models.CharField(blank=True, default='Weekend Table', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_2_title',
            field=models.CharField(blank=True, default='Brunch Club', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_3_badge',
            field=models.CharField(blank=True, default='☕ Geelong West', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_3_img',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_3_sub',
            field=models.CharField(blank=True, default='Open 7 days', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_3_title',
            field=models.CharField(blank=True, default='Our Parlour', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_pass_badge',
            field=models.CharField(blank=True, default='ALL WELCOME', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_pass_sub',
            field=models.CharField(blank=True, default='Priority Seasonal Tastings · Secret Drops · Free Forever', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='club_pass_title',
            field=models.CharField(blank=True, default='FOUNDING MEMBER PASS · NO. 0824', max_length=80),
        ),
    ]
