# Generated by Django 5.2.17 on 2026-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_location_specific_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='club_bento_3_sub',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
